# The URL the site will be built for
base_url = "https://zola-folio.pages.dev"
title = "*folio"
description = "simple whitespace theme"

default_language = "en"
compile_sass = true
build_search_index = true

taxonomies = [
    {name = "tags"}
]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Include mathjax?
math = true

# Put all your custom variables here
menu_items = [
    {name = "about", url = "/pages/about"},
    {name = "projects", url = "/pages/projects"},
    {name = "photography", url = "/pages/photography"},
]

author = "Everett Robinson"
show_only_description = true